### PR TITLE
Fix inconsistencies in category and thread ability checks

### LINKED ISSUE #281: Uncaught Attempted to open modal 'delete-thread' but no such modal found.
Whenever a **user** tries to delete its own created thread by pressing a "Delete" button, this error appears in console:

**Uncaught Attempted to open modal 'delete-thread' but no such modal found.**

However, after pressing CTRL+F5 (refreshing the page) or waiting a few seconds after the thread page loads , this issue disappears

### PR DESCRIPTION
**Pull request by Riari**
This PR fixes several inconsistencies in how category and thread abilities are checked.

## Changelog
+ Updated `ThreadPolicy::delete` and `ThreadPolicy::restore` ability checks so that they're always preceded by `CategoryPolicy::deleteThreads` and `CategoryPolicy::restoreThreads` checks respectively.
+ Updated `Web\CategoryController::show` to compile a list of selectable thread IDs by checking whether the user can move, lock, or pin threads in the category (in which case the list includes all threads in the current page) OR has permission to delete or restore specific threads (in which case the list only includes those threads).
+ Updated `CategoryPolicy::manageThreads` to better reflect whether the user can manage threads in the given category.
+ Updated the `category.show`, `thread.partials.list`, and `thread.show` views:
  + Implemented the new `selectableThreadIds` array to determine which threads should have a checkbox in the `category.show` view.
  + Fixed inconsistent or incorrect ability checks.
  + Fixed some minor style and UX issues.
  + Fixed an issue preventing the bulk thread actions popup from hiding the "Permanently delete" option when the "Delete" action isn't selected.

---

This PR should also fix #281.

### CODE REVIEW

File: src/Http/Controllers/Web/CategoryController.php [hunk 1]
```diff
@@ -62,7 +63,27 @@ public function show(Request $request, Category $category): View
...
-        return ViewFactory::make('forum::category.show', compact('privateAncestor', 'categories', 'category', 'threads'));
+        $selectableThreadIds = [];
+        if ($request->user()) {
+            if (Gate::any(['moveThreadsFrom', 'lockThreads', 'pinThreads'], $category)) {
+                // There are no thread-specific abilities corresponding to these,
+                // so we can include all of the threads for this page
+                $selectableThreadIds = $threads->pluck('id')->toArray();
+            } else {
+                $canDeleteThreads = $request->user()->can('deleteThreads', $category);
+                $canRestoreThreads = $request->user()->can('restoreThreads', $category);
```
Comment (Neehi) [inline src/Http/Controllers/Web/CategoryController.php:74]: If both of these are false you could break out early?

**Review by Neehi — APPROVED** [review]
LGTM. Made one comment but it's not essential.

File: src/Http/Controllers/Web/CategoryController.php (hunk 1 above)
Comment (Riari) [reply src/Http/Controllers/Web/CategoryController.php:74]: Good catch, I'll do that.
